from jsonio import JsonUtil
from submit import BondChain

if __name__ == "__main__":
    # paths
    src_txt = 'test/20201022.txt'  # generated by Tencent QQ
    dst_json = 'test/20201022.json'
    src_bmap = 'assets/bank_map.json'
    src_conf = 'assets/conf.json'
    src_user = 'assets/user.json'
    # convert data to json
    JsonUtil.convert_txt_to_json(src_txt, dst_json, src_bmap)
    # initialize
    bc = BondChain(src_conf, src_user)
    # login
    bc.login()
    # load data
    data = JsonUtil.load(dst_json)
    failed = []
    # traverse data, add one offer each iteration
    for bank in data:
        if not bc.add_offer(bank): failed.append(bank)
    # print failed offers
    if failed:
        print(f'* Totally {len(failed)} failed:')
        for fail in failed:
            print(fail)
    # done and quit
    bc.done()
